name: build
# When the 'permissions' key is specified, unspecified permission scopes (e.g.,
# actions, checks, etc.) are set to no access (none).
permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Run daily (* is a special character in YAML, so quote the string)
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies (macos)
      if: startsWith(matrix.os, 'macos-')
      run: brew install coreutils tree

    - name: Tests
      run: ./tests.sh
